version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/rust-example"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(rust)"

  - package-ecosystem: "cargo"
    directory: "/rust-cf-leptos"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(rust)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(actions)"
